### ISSUE TITLE
volumeClaimTemplate size not used in ElasticSearch manifest

### ISSUE THREAD

**Issue by dr4Ke** [infrawatch/service-telemetry-operator#117]
The generated manifest for the `nodeSets` contains:
```yaml
    volumeClaimTemplate:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
```

The created storage has only 1Gi volumes. It seems that's it's due to a simple syntax error on `volumeClaimTemplate[s]` as it works as expected with:
``` yaml
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
```

I'm not sure if it's the same with `Prometheus` and `Alertmanager` manifests.
