### ISSUE TITLE
Lack of `securityContext` for alertmanager and prometheus volumes

### ISSUE THREAD

**Issue by dr4Ke** [infrawatch/service-telemetry-operator#125]
Is it just me?

A fresh volume mounted for prometheus or alertmanager is not writable to the user (65534) that runs the processes. The root directory of a dynamically created volume is owned by `root` and has `rwxr-xr-x` permissions.

I had to add a `securityContext` for each in custom manifests:
```yaml
spec:
  securityContext:
    fsGroup: 65534
```
