### ISSUE TITLE
default-cloud1-coll-meter-smartgateway-.... keeps crashing

### ISSUE THREAD

**Issue by mrunge** [infrawatch/service-telemetry-operator#175]
With STF 1.2 it seems there is a changed/removed option in sg-core, which is still being used in the container?
 
```
Usage: /sg-core [OPTIONS]

Available options:
flag provided but not defined: -usetimestamp
  -config string
    	configuration file path (default "/etc/sg-core.conf.yaml")
  -cpuprofile string
    	write cpu profile to file


Default configurations:

plugindir: /usr/lib64/sg-core/
loglevel: info
handlererrors: false
transports: []
applications: []
```

Looking into the smart gateway operator, the deployment for `default-cloud1-coll-meter-smartgateway`
lists
```
       - name: smart-gateway
          image: 'quay.io/infrawatch/sg-core:latest'
          args:
            - '-usetimestamp'
            - '-promhost'
            - 0.0.0.0
            - unix
            ```
