### ISSUE TITLE
STF won't install without cluster-monitoring-operator installed (workaround within)

### ISSUE THREAD

**Issue by csibbitt** [infrawatch/service-telemetry-operator#306]
Not usually a problem since it's installed by default, but not on CRC.

```
TASK [Bind the local prometheus SA to prometheus cluster role] ******************************** 
fatal: [localhost]: FAILED! => {"changed": false, "error": 404, "msg": "Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"clusterroles.rbac.authorization.k8s.io \\\\\"prometheus-k8s\\\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"prometheus-k8s\",\"group\":\"rbac.authorization.k8s.io\",\"kind\":\"clusterroles\"},\"code\":404}\\n'", "reason": "Not Found", "status": 404}
```
needs https://paste.opendev.org/show/812354/

```
 TASK [Bind role] ******************************** 
fatal: [localhost]: FAILED! => {"changed": false, "error": 404, "msg": "Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"clusterroles.rbac.authorization.k8s.io \\\\\"alertmanager-main\\\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"alertmanager-main\",\"group\":\"rbac.authorization.k8s.io\",\"kind\":\"clusterroles\"},\"code\":404}\\n'", "reason": "Not Found", "status": 404}
```
needs https://paste.opendev.org/show/812355/

**Comment by leifmadsen** [comment]
Noting because I don't trust the pastebins:

812354

```yaml
apiVersion: rbac.authorization.k8s.io/v1                                                                                                                                        [17/1814]
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  resources:
  - securitycontextconstraints
  verbs:
  - use
```

812355

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertmanager-main
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  resources:
  - securitycontextconstraints
  verbs:
  - use
```
